version: '3'

services:
  web:
    build: .
    image: flask-postgres-app
    container_name: flask-app
    ports:
      - "8080:5000"
    depends_on:
      - db
    networks:
      - mynet

  db:
    image: postgres:16.0
    container_name: postgres-db
    environment:
      POSTGRES_DB: UserCredentials
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # Mount a local directory containing initialization scripts
    ports:
      - "5432:5432"  # Mapping the PostgreSQL container port to your local machine port
    networks:
      - mynet

networks:
  mynet:

volumes:
  postgres-data:
